package com.ucsal.gestaoAula.model;

public enum Curso {

	 
	ADMINISTRAÇÃO,
	ANALISE_E_DESENVOLVIMENTO_DE_SISTEMAS,
	ARQUITETURA_E_URBANISMO,
	BIOMEDICINA,
	CIENCIAS_BIOLOGICAS,
	CIENCIAS_CONTABEIS,
	COMUNICACAO,
	DIREITO,
	EDUCACAO_FISICA,
	ENFERMAGEM,
	ENGENHARIA_CIVIL,
	ENGENHARIA_DE_SOFTWARE,
	ENGENHARIA_MECANICA,
	ENGENHARIA_QUIMICA,
	FILOSOFIA,
	FISIOTERAPIA,
	GASTRONOMIA,
	GEOGRAFIA,
	HISTÓRIA,
	LETRAS,
	MATEMÁTICA,
	MÚSICA,
	NUTRIÇÃO,
	PEDAGOGIA,
	PSICOLOGIA,
	RECURSOS_HUMANOS,
	SERVICO_SOCIAL,
	TEOLOGIA



}
